name: fetch_polls

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01,13 * * *' # runs at 6 am and 6 pm Pacific everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install python version
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run fetch_harris_trump.py to get the latest average  
        run: |
          python fetch_harris_trump.py
          python fetch_harris_trump_archive.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
