name: fetch_polls

on:
  workflow_dispatch:
  schedule:
    - cron: '00 1,7,13 * * *' 
    # Daily at 6 am, noon and 6 pm Pacific

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout repo

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: install python packages
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          set -e
          python fetch_harris_trump.py
          python make_harris_trump_trend.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: commit files
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"

      - name: push changes
        run: |
          set -e  # Stop execution if a command fails
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
